FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt . 
# no cache directory command argument doesnt create a cache which pip normally creates, it makes the image smalelr. 
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
# the 0.0.0.0 anyone can access as the container allows traffic else it listens only for the local traffic, which we cant acceses. 
CMD [ "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000" ]
